### ISSUE TITLE
Update docker configuration

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#408]
We currently have this outdated [Docker wiki](https://github.com/begriffs/postgrest/wiki/Docker) describing how to dockerize postgrest. I think what we want are two distinct configurations:

1. Dev/test mode. This is a single container for running tests on CI as well as for local development for anyone who wants to develop that way.
  * built on top of https://hub.docker.com/r/fpco/stack-build/ 
  * add postgresql 9.5
2. Deployment mode. This is a few containers put together with docker-compose
  * Include a docker-compose configuration to tie the following things together
  * A small container just for postgrest, based off something like busybox. Would take parameters for the database to use etc. No other services installed there.
    * have the container download pre-built binary from [project release page](https://github.com/begriffs/postgrest/releases) based on version parameter
  * A container for postgresql, https://hub.docker.com/_/postgres/ and a persistent data volume
    * or an [external_link](https://docs.docker.com/compose/compose-file/#external-links) to Amazon RDS
  * A container for nginx, https://hub.docker.com/_/nginx/ with supplied config
    * enforce SSL-only
    * rewrite `/table/:id` to `/table?id=eq.:id` + prefer plurality header
    * safeguards for using DELETE or PATCH against entire (unfiltered) tables
    * disguised server identification header
    * prevent DoS uploads with client_max_body_size

The fancy nginx config items aren't required for the initial solution. But we probably want those three containers to be composed for production.

**Comment by KoRiGaN** [comment]
I tend to minimise differences between dev/test and deployment mode. 

At the moment and for dev/test purpose I'm using something that looks like the configuration 2).
A Dockerfile to build a small container just for postgrest, based on ubuntu 14.04 (any distro will do). I'm sure we can use other disto. The image is built by downloading pre-built binary from project release page based on version parameter.

```
FROM ubuntu:14.04
MAINTAINER Mickael Bouchaud <bouchaud.mickael@gmail.com>

ENV POSTGREST_VERSION 0.3.0.1
ENV POSTGREST_DBHOST host
ENV POSTGREST_DBPORT 5432
ENV POSTGREST_DBNAME database
ENV POSTGREST_DBUSER user
ENV POSTGREST_DBPASS password

RUN apt-get update
RUN apt-get install -y tar xz-utils wget libpq-dev
RUN apt-get update

RUN wget http://github.com/begriffs/postgrest/releases/download/v${POSTGREST_VERSION}/postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
RUN tar --xz -xvf postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
RUN mv postgrest /usr/local/bin/postgrest

CMD postgrest postgres://${POSTGREST_DBUSER}:${POSTGREST_DBPASS}@${POSTGREST_DBHOST}:${POSTGREST_DBPORT}/${POSTGREST_DBNAME} \
              --port 3000 \
              --anonymous postgres \
              --schema public

EXPOSE 3000

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```
and a docker-compose.yml for Postgrest and Postgres
```
stgrest:
  image: boumi/postgrest
  ports:
    - "3000:3000"
  environment:
    POSTGREST_VERSION: 0.3.0.1
    POSTGREST_DBHOST: postgres
    POSTGREST_DBPORT: 5432
    POSTGREST_DBNAME: app_db
    POSTGREST_DBUSER: app_user
    POSTGREST_DBPASS: password
  links:
    - postgres:postgres

postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: app_db
    POSTGRES_USER: app_user
    POSTGRES_PASSWORD: password
```
With these two files a docker build and docker compose up are only requiered to get up and running.

**Comment by danielxvu** [comment]
KoRiGan: Any reason why you build the PostgREST Dockerfile separately?

```

**Comment by danielxvu** [comment]
KoRiGan: Any reason why you build your PostgREST container separately? I just keep the Dockerfile in the same repository and use ```docker-compose build``` to handle any changes in either the PostgREST or PostgreSQL Dockerfiles.

```
api:
  build: ./postgrest/
  ports:
    - 3000:3000
  links:
    - db
  restart: always
db:
  build: ./postgresql/
  environment:
    POSTGRES_PASSWORD: foobar
  ports:
  - 5432:5432
```

Source (no Nginx container specified): https://github.com/danielxvu/docker-postgrest-with-postgresql

**Comment by KoRiGaN** [comment]
@danielxvu  no reason really. Your solution looks great

**Comment by jackfirth** [comment]
> have the container download pre-built binary from project release page based on version parameter

When would this download occur? Would the container download the binary upon startup, or would it download it as part of building the image? If it's downloaded during the container start time, if someone deploys a fleet of identical postgrest containers for load balancing the work will be massively duplicated. Additionally, starting up containers is usually presumed to not involve large-download IO to install things, that's usually reserved for build time.

The disadvantage to downloading during the image building process is that the version isn't in the client's control, so we'd need to provide a separate Docker image for each version. This can be made easier by having a single base image that uses an `ONBUILD` command that downloads the binary based on a version variable and having one derived image per version that just sets the version variable.

**Comment by jackfirth** [comment]
Just to clarify, with a docker image for each postgrest version, the example docker-compose.yml above would look like this for the postgrest service:

```yaml
stgrest:
  image: boumi/postgrest:0.3.0.1
  ports:
    - "3000:3000"
  environment:
    POSTGREST_DBHOST: postgres
    POSTGREST_DBPORT: 5432
    POSTGREST_DBNAME: app_db
    POSTGREST_DBUSER: app_user
    POSTGREST_DBPASS: password
  links:
    - postgres:postgres
```
