### ISSUE TITLE
docker-compose dosn't load postgrest.conf file

### ISSUE THREAD

**Issue by xamika** [begriffs/postgrest#819]
I was trying to use posgrest in a docker container. I used The instruction on this page: https://github.com/begriffs/postgrest/tree/master/docker but it isn't working. I mounted the config.conf file to /etc/postgrest.conf. This is working but postgrest doesn't load this config file from etc/postgrest.conf.

**Comment by ruslantalpa** [comment]
make sure you are using the latest version (4.0)
looking at the tags in docker i think you need to use "nightly" tag

**Comment by xamika** [comment]
Thank you for you response. I updated my docker-compose file:
```
  postgrest:
    image: begriffs/postgrest:nightly
    ports:
     - '3000:3000'
    links:
     - postgres
    volumes:
     - ./conf/postgrest.conf:/etc/postgrest.conf
```
but now I receive another error XD:
`postgrest_1  | Missing: FILENAME
postgrest_1  | 
postgrest_1  | Usage: postgrest FILENAME
postgrest_1  |   PostgREST 0.4.0.0 / create a REST API to an existing Postgres database
postgrest_1  | 
postgrest_1  | Available options:
postgrest_1  |   -h,--help                Show this help text
postgrest_1  |   FILENAME                 Path to configuration file
postgrest_1  | 
`

**Comment by ruslantalpa** [comment]
can you try and build the image on your computer from this definition?
https://github.com/begriffs/postgrest/blob/master/docker/Dockerfile

i am not sure what exactly how that nightly image was built
(the docker for the latest version is not quite right yet, there is still a discussion of how to get it up to date)

**Comment by xamika** [comment]
I solved my problem with a workarround (I'm overrwriting the postgrest command):

```
postgrest:
    image: begriffs/postgrest:nightly
    ports:
     - '3000:3000'
    links:
     - postgres
    volumes:
     - ./conf/postgrest.conf:/etc/postgrest.conf
    command: postgrest /etc/postgrest.conf
```
Please add the path to your command. https://hub.docker.com/r/begriffs/postgrest/builds/bwxqmc8rj3ygeycorkarnq8/

**Comment by begriffs** [comment]
Good workaround. The `latest` image on docker hub is not working right for 0.4 because we're still deciding the best way to do things for the new version.

**Comment by begriffs** [comment]
I rebuilt the nightly image to pick up the [change](https://github.com/begriffs/postgrest/blob/master/docker/Dockerfile#L16) that ensures it passes in a config file path to the binary. Although we still have more work to do to support environment variables, this will enable the basic case of mapping in a config file like you're doing. Thanks for reporting the problem.

**Comment by switch-to-gitlab** [comment]
@begriffs I ran into the same issue and fixed it with the same "command" fix.

**Comment by tnoms** [comment]
I ran into this issue as well trying to get up and running. I spent quite a while searching through the documentation for how to reference a config file when using Docker or Docker Compose. I did not find this information documented.  
  
Please consider adding a Docker Compose example like the one below to the official documentation for Installation or Configuration:  
  
```
postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    depends_on:
      - postgres_db_container
    volumes:
      - /user_defined_location/postgrest.conf:/etc/postgrest.conf
    ports:
      - 3000:3000
    command: postgrest /etc/postgrest.conf
    restart: unless-stopped
```
